from __future__ import annotations

import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec is not None and spec.loader is not None
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


sync_hf_to_website_data = load_module(
    "sync_hf_to_website_data",
    ROOT / "scripts" / "sync_hf_to_website_data.py",
)
validate_website_data = load_module(
    "validate_website_data",
    ROOT / "scripts" / "validate_website_data.py",
)


class WebsitePromptRenderingTest(unittest.TestCase):
    def question(self, *, desc_level: str, task_type: str, samples: int) -> dict[str, Any]:
        key = f"{desc_level}-{task_type}-{samples}"
        return {
            "recipe_info": {
                "desc_level": desc_level,
                "type_of_request": task_type,
                "number_train_samples_per_class": samples,
            },
            "question_text": {
                "sample_source": f"prompt source {key}",
                "ordered_field_agent_prompt": [["sample_source", ""]],
            },
        }

    def write_questions(self, path: Path) -> None:
        questions = {}
        for desc_level in ("high", "none"):
            for task_type in ("direct", "code"):
                for samples in (0, 1, 3):
                    questions[f"{desc_level}-{task_type}-{samples}"] = self.question(
                        desc_level=desc_level,
                        task_type=task_type,
                        samples=samples,
                    )
        path.write_text(json.dumps({"questions": questions}), encoding="utf-8")

    def test_prompt_combinations_are_rendered_from_question_text(self) -> None:
        def fake_renderer(question_text: dict[str, Any], *, question_slug: str, questions_by_id: dict[str, Any]) -> str:
            self.assertIn(question_slug, questions_by_id)
            return f"rendered::{question_slug}::{question_text['sample_source']}"

        with tempfile.TemporaryDirectory() as tmp:
            questions_path = Path(tmp) / "questions.json"
            self.write_questions(questions_path)

            combinations = sync_hf_to_website_data.rendered_prompt_combinations(questions_path, fake_renderer)

        self.assertEqual(len(combinations), 12)
        by_key = {
            (item["desc_level"], item["task_type"], item["training_samples"]): item["agent_instruction"]
            for item in combinations
        }
        self.assertEqual(
            by_key[("high", "direct", "none")],
            "rendered::high-direct-0::prompt source high-direct-0",
        )
        self.assertEqual(
            by_key[("none", "code", "one")],
            "rendered::none-code-1::prompt source none-code-1",
        )
        self.assertEqual(
            by_key[("none", "code", "multiple")],
            "rendered::none-code-3::prompt source none-code-3",
        )

    def test_missing_tsenv_checkout_uses_local_documented_renderer(self) -> None:
        original_candidate_roots = sync_hf_to_website_data.candidate_tsenv_roots
        sync_hf_to_website_data.candidate_tsenv_roots = lambda explicit_root: [Path("/does/not/exist")]
        try:
            renderer = sync_hf_to_website_data.load_prompt_renderer(None)
        finally:
            sync_hf_to_website_data.candidate_tsenv_roots = original_candidate_roots

        rendered = renderer(
            {
                "sample_source": "The time series were generated",
                "environment_description": "by simulating a test system.",
                "observed_columns": "",
                "ordered_field_agent_prompt": [
                    ["sample_source", " "],
                    ["environment_description", "\n\n"],
                    ["observed_columns", ""],
                ],
            }
        )

        self.assertEqual(rendered, "The time series were generated by simulating a test system.")

    def test_explicit_tsenv_root_imports_shared_prompt_renderer(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tsenv_root = Path(tmp)
            shared_dir = tsenv_root / "shared"
            shared_dir.mkdir()
            (shared_dir / "__init__.py").write_text("", encoding="utf-8")
            (shared_dir / "prompts.py").write_text(
                "\n".join(
                    [
                        "def render_tsenv_agent_prompt(question_text, **kwargs):",
                        "    return 'external::' + question_text['sample_source']",
                    ]
                ),
                encoding="utf-8",
            )

            previous_shared = sys.modules.pop("shared", None)
            previous_prompts = sys.modules.pop("shared.prompts", None)
            try:
                renderer = sync_hf_to_website_data.load_prompt_renderer(tsenv_root)
            finally:
                sys.modules.pop("shared", None)
                sys.modules.pop("shared.prompts", None)
                if str(tsenv_root) in sys.path:
                    sys.path.remove(str(tsenv_root))
                if previous_shared is not None:
                    sys.modules["shared"] = previous_shared
                if previous_prompts is not None:
                    sys.modules["shared.prompts"] = previous_prompts

        self.assertEqual(renderer({"sample_source": "prompt source"}), "external::prompt source")

    def test_sync_overwrites_stale_hf_prompt_combinations_from_questions(self) -> None:
        def fake_renderer(question_text: dict[str, Any], *, question_slug: str, questions_by_id: dict[str, Any]) -> str:
            self.assertIn(question_slug, questions_by_id)
            return f"rendered::{question_slug}::{question_text['sample_source']}"

        def fake_download_file(url: str, destination: Path) -> None:
            destination.parent.mkdir(parents=True, exist_ok=True)
            if "website/summary.json" in url:
                destination.write_text(json.dumps({"simulators": ["BallDrop"]}), encoding="utf-8")
            elif "website/leaderboard.json" in url:
                destination.write_text(json.dumps({"rows": [], "filters": {}}), encoding="utf-8")
            elif "website/environments/BallDrop/description.json" in url:
                destination.write_text(
                    json.dumps(
                        {
                            "name": "BallDrop",
                            "short_one_line_description": "short",
                            "prompt_combinations": [
                                {
                                    "desc_level": "high",
                                    "task_type": "direct",
                                    "training_samples": "none",
                                    "agent_instruction": "stale deployed prompt",
                                }
                            ],
                        }
                    ),
                    encoding="utf-8",
                )
            elif "questions/BallDrop/questions.json" in url:
                self.write_questions(destination)
            elif "website/environments/BallDrop/data_" in url:
                destination.write_text(json.dumps({"rows": [], "intervention_time": 0.0}), encoding="utf-8")
            elif "website/submissions_manifest.txt" in url:
                destination.write_text("", encoding="utf-8")
            else:
                self.fail(f"unexpected download URL: {url}")

        original_simulators = sync_hf_to_website_data.SIMULATORS
        original_download_file = sync_hf_to_website_data.download_file
        original_load_prompt_renderer = sync_hf_to_website_data.load_prompt_renderer
        sync_hf_to_website_data.SIMULATORS = ("BallDrop",)
        sync_hf_to_website_data.download_file = fake_download_file
        sync_hf_to_website_data.load_prompt_renderer = lambda tsenv_root: fake_renderer
        try:
            with tempfile.TemporaryDirectory() as tmp:
                output_dir = Path(tmp) / "data"
                sync_hf_to_website_data.sync_from_hf("repo", "main", output_dir, None)
                description = json.loads(
                    (output_dir / "environments" / "BallDrop" / "description.json").read_text(encoding="utf-8")
                )
                homepage_data = json.loads(
                    (output_dir / "environments" / "data_main_page.json").read_text(encoding="utf-8")
                )
        finally:
            sync_hf_to_website_data.SIMULATORS = original_simulators
            sync_hf_to_website_data.download_file = original_download_file
            sync_hf_to_website_data.load_prompt_renderer = original_load_prompt_renderer

        self.assertEqual(homepage_data["source"], "programmatic:ball-drop-bounce-gif")
        self.assertTrue(homepage_data["rows"])
        combinations = description["prompt_combinations"]
        self.assertEqual(len(combinations), 12)
        self.assertNotEqual(combinations[0]["agent_instruction"], "stale deployed prompt")
        self.assertEqual(
            combinations[0]["agent_instruction"],
            "rendered::high-direct-0::prompt source high-direct-0",
        )

    def test_positive_prompt_bucket_falls_back_when_exact_count_missing(self) -> None:
        questions = {
            "high-code-0": self.question(desc_level="high", task_type="code", samples=0),
            "high-code-3": self.question(desc_level="high", task_type="code", samples=3),
        }

        selected_one_slug, _ = sync_hf_to_website_data.select_question(
            questions,
            desc_level="high",
            task_type="code",
            training_samples="one",
        )
        selected_multiple_slug, _ = sync_hf_to_website_data.select_question(
            questions,
            desc_level="high",
            task_type="code",
            training_samples="multiple",
        )

        self.assertEqual(selected_one_slug, "high-code-3")
        self.assertEqual(selected_multiple_slug, "high-code-3")

    def test_validator_rejects_missing_prompt_combination(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "summary.json").write_text(
                json.dumps(
                    {
                        "simulators": ["BallDrop", "BounceBall", "MassSlide"],
                        "canonical_scope": {
                            "task_mode": "Code",
                            "noise": "Low",
                            "context": "High",
                            "examples": "Three Examples",
                        },
                    }
                ),
                encoding="utf-8",
            )
            (root / "leaderboard.json").write_text(json.dumps({"rows": [], "filters": {}}), encoding="utf-8")
            (root / "environments").mkdir()
            sync_hf_to_website_data.write_homepage_data(root / "environments")
            for simulator in ("BallDrop", "BounceBall", "MassSlide"):
                env_dir = root / "environments" / simulator
                env_dir.mkdir(parents=True)
                (env_dir / "description.json").write_text(
                    json.dumps(
                        {
                            "name": simulator,
                            "short_one_line_description": "short",
                            "download_link": (
                                "https://huggingface.co/datasets/eth-siplab/tsenvbenchmark/tree/main/"
                                f"questions/{simulator}"
                            ),
                            "prompt_combinations": [
                                {
                                    "desc_level": "high",
                                    "task_type": "direct",
                                    "training_samples": "none",
                                    "agent_instruction": "rendered prompt",
                                }
                            ],
                            "sample_count": 1,
                        }
                    ),
                    encoding="utf-8",
                )
                for sample_number in range(1, 6):
                    (env_dir / f"data_{sample_number}.json").write_text(
                        json.dumps({"rows": [{"time": 0.0}], "intervention_time": 0.0}),
                        encoding="utf-8",
                    )

            with self.assertRaises(validate_website_data.ValidationError):
                validate_website_data.validate(root)

    def test_validator_rejects_missing_homepage_data(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "summary.json").write_text(
                json.dumps(
                    {
                        "simulators": ["BallDrop", "BounceBall", "MassSlide"],
                        "canonical_scope": {
                            "task_mode": "Code",
                            "noise": "Low",
                            "context": "High",
                            "examples": "Three Examples",
                        },
                    }
                ),
                encoding="utf-8",
            )
            (root / "leaderboard.json").write_text(json.dumps({"rows": [], "filters": {}}), encoding="utf-8")
            (root / "environments").mkdir()

            with self.assertRaisesRegex(validate_website_data.ValidationError, "data_main_page.json"):
                validate_website_data.validate(root)

    def test_validator_rejects_stale_deployed_prompt_prefix(self) -> None:
        stale_prompt = (
            "You are given multivariate time-series observations from BallDrop.\n\n"
            "Identify which physical parameter changed, or answer that no intervention occurred."
        )
        with self.assertRaises(validate_website_data.ValidationError):
            validate_website_data.validate_prompt_combinations(
                [
                    {
                        "desc_level": desc_level,
                        "task_type": task_type,
                        "training_samples": training_samples,
                        "agent_instruction": stale_prompt if index == 0 else "rendered prompt",
                    }
                    for index, (desc_level, task_type, training_samples) in enumerate(
                        sorted(validate_website_data.EXPECTED_PROMPT_COMBINATIONS)
                    )
                ],
                "BallDrop",
            )


if __name__ == "__main__":
    unittest.main()
